site_name: KonverterMap
site_url: https://olstecnologia.github.io/KonverterMap
repo_url: https://github.com/olstecnologia/KonverterMap
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.indexes

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration:
      - CreateMap: config-create-map.md
      - ForMember: config-for-member.md
      - Ignore: config-ignore.md
      - When: config-when.md
      - ReverseMap: config-reverse-map.md
      - BeforeMap: config-before-map.md
      - AfterMap: config-after-map.md
  - Real Examples:
      - User Full Name: exemplo-nome-completo.md
      - Order List: exemplo-pedidos.md
      - Recursive Pessoa: exemplo-pessoa-responsavel.md
  - Changelog: changelog.md
